CREATE TABLE BENCH_ARCHIVOS_BBVA(
	NRO_OPERACION VARCHAR(25),
	NRO_CLIENTE VARCHAR(25),
	DEUDA NUMERIC(12,2),
	PAGO NUMERIC(12,2),
	MONEDA VARCHAR(25),
	SEGMENTO VARCHAR(25),
	DA INTEGER,
	TIPO_PRODUCTO VARCHAR(100),
	FECHA_BENCH DATE	
);

